function Jaipur() {
	return (
		<div>
			<h1>Jaipur</h1>

			<h2>
				<a
					href="https://jaipur-987f936505cd.herokuapp.com/games/5"
					target="blank"
					rel="noreferrer"
					className="underline active:text-blue active:font-bold"
				>
					Play it on Heroku
				</a>
			</h2>
			<h2>Brief</h2>
			<p>
				This solo project full-stack project was built as refresher for the
				Ruby-on-rails framework. It was built in 14 days. I wanted to build
				something fun and visually appealing to also flex my front end skills. I
				chose to build a clone of the card game Jaipur. The game is a two player
				game and the rules are included on the opening screen. The game was
				built using Ruby on Rails, HTML, CSS, Hotwire and Tailwind CSS. The
				images were generated by AI. The game was built using the MVC pattern.
				Game state is managed by a Postgresql database.
			</p>
			<p>Image of Jaipur</p>
			<p>Link to Jaipur</p>
			<p>Link to Github</p>
		</div>
	);
}

export default Jaipur;
